version: 2
jobs:
    build-docs:
        docker:
            - image: python:3.7
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: pip install mkdocs
            - run:
                name: Build docs
                command: mkdocs build
            - persist_to_workspace:
                root: html_docs
                paths: site
            - store_artifacts:
                path: html_docs/site
                destination: html
    deploy-docs:
        docker:
            - image: node:8.10.0
        steps:
            - checkout
            - attach_workspace:
                at: html_docs
            - run:
                name: Disable jekyll builds
                command: touch html_docs/site/.nojekyll
            - run:
                name: Install and configure dependencies
                command: |
                  npm install -g --silent gh-pages@2.0.1
                  git config user.email "monkeyman192@github.com"
                  git config user.name "circle CI"
            - add_ssh_keys:
                fingerprints:
                    - "b8:e8:81:0e:63:56:1b:b6:00:8f:7a:96:22:e6:74:0d"
            - run:
                name: Deploy docs to gh-pages branch
                command: gh-pages --dotfiles --message "[skip ci] Auto-update" --dist html_docs/site
    build-addon:
        docker:
            - image: python:3.7
        steps:
            - checkout
            - run:
                name: Build zip
                command: python ./tools/build.py
            - store_artifacts:
                path: build/nmsdk.zip
                destination: build/nmsdk.zip
            - persist_to_workspace:
                root: build
                paths: nmsdk.zip
    release-addon:
        docker:
            - image: circleci/node:4.8.2
        steps:
          - checkout
          - attach_workspace:
              at: build
          - run:
              name: ensure script is executable
              command: chmod +x ./tools/upload-github-release-asset.sh
          - run:
              name: run script
              command: bash ./tools/upload-github-release-asset.sh github_api_token=${GITHUB_TOKEN} owner=monkeyman192 repo=NMSDK filename=./build/nmsdk.zip
            
workflows:
    version: 2
    build:
        jobs:
            - build-docs
            - deploy-docs:
                requires:
                    - build-docs
                filters:
                    branches:
                        only: master
            - build-addon
            - release-addon:
                requires:
                    - build-addon
                filters:
                    branches:
                        only: master
